import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def openform(self):
        from FOURTEEN import Ui_Form
        self.Form = QtWidgets.QWidget()
        self.ui = Ui_Form()
        self.ui.setupUi(self.Form)
        self.Form.show()
    def reportfunction(self):
        name = self.lineEdit.text()
        type = self.comboBox.currentText()
        date = self.comboBox_2.currentText()
        month = self.comboBox_4.currentText()
        year = self.comboBox_3.currentText()
        status = self.lineEdit_2.text()

        if len(name) == 0 or len(status) == 0:
            self.label_2.setText("please fill all the required field ")


        else:
            conn = sqlite3.connect('report.db')
            cur = conn.cursor()
            user_info = [name, type, date, month, year, status]
            cur.execute('INSERT INTO rep(clientname,type,date,month,year,currentstatus) VALUES (?,?,?,?,?,?)',user_info)

            conn.commit()
            conn.close()
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(521, 497)
        Form.setMaximumSize(QtCore.QSize(598, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(-10, 0, 551, 600))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 0, 541, 501))
        self.label.setMaximumSize(QtCore.QSize(541, 501))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("border-image: url(C:/Users/F I ENTERPRISES/Documents/ise project/ise project 2k22/login.jpeg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(220, 370, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 10, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(200, 220, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(200, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_9.setObjectName("label_9")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(200, 160, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setGeometry(QtCore.QRect(220, 100, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QLineEdit {\n"
" border: 2.5px solid gray;\n"
" border-radius: 7px;\n"
" background-color: rgb(214, 214, 214);\n"
"    \n"
"    \n"
"    color: rgb(113, 113, 113)\n"
"}")
        self.comboBox.setEditable(False)
        self.comboBox.setMaxVisibleItems(10)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setItemText(2, "")
        self.comboBox.addItem("")
        self.comboBox.setItemText(3, "")
        self.comboBox_2 = QtWidgets.QComboBox(self.widget)
        self.comboBox_2.setGeometry(QtCore.QRect(130, 270, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("QLineEdit {\n"
" border: 2.5px solid gray;\n"
" border-radius: 7px;\n"
" background-color: rgb(214, 214, 214);\n"
"    \n"
"    \n"
"    color: rgb(113, 113, 113)\n"
"}")
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setMaxVisibleItems(10)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(31, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(32, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(33, "")
        self.comboBox_3 = QtWidgets.QComboBox(self.widget)
        self.comboBox_3.setGeometry(QtCore.QRect(350, 270, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("QLineEdit {\n"
" border: 2.5px solid gray;\n"
" border-radius: 7px;\n"
" background-color: rgb(214, 214, 214);\n"
"    \n"
"    \n"
"    color: rgb(113, 113, 113)\n"
"}")
        self.comboBox_3.setEditable(False)
        self.comboBox_3.setMaxVisibleItems(10)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.setItemText(5, "")
        self.comboBox_3.addItem("")
        self.comboBox_3.setItemText(6, "")
        self.comboBox_4 = QtWidgets.QComboBox(self.widget)
        self.comboBox_4.setGeometry(QtCore.QRect(240, 270, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setStyleSheet("QLineEdit {\n"
" border: 2.5px solid gray;\n"
" border-radius: 7px;\n"
" background-color: rgb(214, 214, 214);\n"
"    \n"
"    \n"
"    color: rgb(113, 113, 113)\n"
"}")
        self.comboBox_4.setEditable(False)
        self.comboBox_4.setMaxVisibleItems(10)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.setItemText(11, "")
        self.comboBox_4.addItem("")
        self.comboBox_4.setItemText(12, "")
        self.comboBox_4.addItem("")
        self.comboBox_4.setItemText(13, "")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(180, 60, 194, 22))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(160, 410, 241, 41))
        self.label_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 330, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_3.clicked.connect(self.reportfunction)
        self.pushButton_4.clicked.connect(self.openform)
        self.pushButton_4.clicked.connect(Form.close)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_3.setText(_translate("Form", "Submit"))
        self.pushButton_4.setText(_translate("Form", "BACK"))
        self.label_6.setText(_translate("Form", "project completon date"))
        self.label_9.setText(_translate("Form", "REPORT"))
        self.lineEdit.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Client Name"))
        self.comboBox.setItemText(0, _translate("Form", "Architect"))
        self.comboBox.setItemText(1, _translate("Form", "Contractor"))
        self.comboBox_2.setItemText(0, _translate("Form", "1"))
        self.comboBox_2.setItemText(1, _translate("Form", "2"))
        self.comboBox_2.setItemText(2, _translate("Form", "3"))
        self.comboBox_2.setItemText(3, _translate("Form", "4"))
        self.comboBox_2.setItemText(4, _translate("Form", "5"))
        self.comboBox_2.setItemText(5, _translate("Form", "6"))
        self.comboBox_2.setItemText(6, _translate("Form", "7"))
        self.comboBox_2.setItemText(7, _translate("Form", "8"))
        self.comboBox_2.setItemText(8, _translate("Form", "9"))
        self.comboBox_2.setItemText(9, _translate("Form", "10"))
        self.comboBox_2.setItemText(10, _translate("Form", "11"))
        self.comboBox_2.setItemText(11, _translate("Form", "12"))
        self.comboBox_2.setItemText(12, _translate("Form", "13"))
        self.comboBox_2.setItemText(13, _translate("Form", "14"))
        self.comboBox_2.setItemText(14, _translate("Form", "15"))
        self.comboBox_2.setItemText(15, _translate("Form", "16"))
        self.comboBox_2.setItemText(16, _translate("Form", "17"))
        self.comboBox_2.setItemText(17, _translate("Form", "18"))
        self.comboBox_2.setItemText(18, _translate("Form", "19"))
        self.comboBox_2.setItemText(19, _translate("Form", "20"))
        self.comboBox_2.setItemText(20, _translate("Form", "21"))
        self.comboBox_2.setItemText(21, _translate("Form", "22"))
        self.comboBox_2.setItemText(22, _translate("Form", "23"))
        self.comboBox_2.setItemText(23, _translate("Form", "24"))
        self.comboBox_2.setItemText(24, _translate("Form", "25"))
        self.comboBox_2.setItemText(25, _translate("Form", "26"))
        self.comboBox_2.setItemText(26, _translate("Form", "27"))
        self.comboBox_2.setItemText(27, _translate("Form", "28"))
        self.comboBox_2.setItemText(28, _translate("Form", "29"))
        self.comboBox_2.setItemText(29, _translate("Form", "30"))
        self.comboBox_2.setItemText(30, _translate("Form", "31"))
        self.comboBox_3.setItemText(0, _translate("Form", "2023"))
        self.comboBox_3.setItemText(1, _translate("Form", "2024"))
        self.comboBox_3.setItemText(2, _translate("Form", "2025"))
        self.comboBox_3.setItemText(3, _translate("Form", "2026"))
        self.comboBox_3.setItemText(4, _translate("Form", "2027"))
        self.comboBox_4.setItemText(0, _translate("Form", "jan"))
        self.comboBox_4.setItemText(1, _translate("Form", "feb"))
        self.comboBox_4.setItemText(2, _translate("Form", "mar"))
        self.comboBox_4.setItemText(3, _translate("Form", "may"))
        self.comboBox_4.setItemText(4, _translate("Form", "jun"))
        self.comboBox_4.setItemText(5, _translate("Form", "jul"))
        self.comboBox_4.setItemText(6, _translate("Form", "aug"))
        self.comboBox_4.setItemText(7, _translate("Form", "sep"))
        self.comboBox_4.setItemText(8, _translate("Form", "oct"))
        self.comboBox_4.setItemText(9, _translate("Form", "nov"))
        self.comboBox_4.setItemText(10, _translate("Form", "dec"))
        self.lineEdit_2.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Current Status"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
