# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'five1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def openform1(self):
        from four2 import Ui_Formsss
        self.Form = QtWidgets.QWidget()
        self.ui = Ui_Formsss()
        self.ui.setupUi(self.Form)
        self.Form.show()

    def requirementfunction(self):
        place = self.comboBox.currentText()
        direction = self.comboBox_2.currentText()
        type = self.comboBox_3.currentText()
        name = self.lineEdit_8.text()
        location = self.lineEdit_4.text()
        yards = self.lineEdit_3.text()
        date = self.lineEdit_5.text()
        room = self.lineEdit_2.text()
        floor = self.lineEdit_6.text()
        parking = self.lineEdit_7.text()

        if len(place) == 0 or len(direction) == 0 or len(type) == 0 or len(name) == 0 or len(location) == 0 or len(
                yards) == 0 or len(date) == 0 or len(room) == 0 or len(floor) == 0 or len(parking) == 0:
            self.label_2.setText("please fill all the required field ")
        else:
            # self.pushButton_3.clicked.connect(self.openform2)
            conn = sqlite3.connect('requirement.db')
            cur = conn.cursor()
            # self.pushButton_3.clicked.connect(self.openform2)
            user_info = [place, direction, type, name, location, yards, date, room, floor, parking]
            cur.execute(
                'INSERT INTO req(place,direction,type,name,location,yards,date,room,floor,parking) VALUES (?,?,?,?,?,?,?,?,?,?)',
                user_info)

            conn.commit()
            conn.close()
            self.label_2.setText("your requirement is submitted  ")

    def openform2(self):
        from eight1 import Ui_Form
        self.Form = QtWidgets.QWidget()
        self.ui = Ui_Form()
        self.ui.setupUi(self.Form)
        self.Form.show()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(521, 501)
        Form.setMaximumSize(QtCore.QSize(598, 16777215))
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(-10, 0, 551, 600))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(-4, -8, 541, 501))
        self.label.setMaximumSize(QtCore.QSize(541, 501))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("border-image: url(C:/Users/F I ENTERPRISES/Documents/ise project/ise project 2k22/login.jpeg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(100, 10, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgba(255, 255, 255, 210);")
        self.label_4.setObjectName("label_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 100, 341, 341))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QLineEdit {\n"
" border: 2.5px solid gray;\n"
" border-radius: 7px;\n"
" background-color: rgb(214, 214, 214);\n"
"    \n"
"    \n"
"    color: rgb(113, 113, 113)\n"
"}")
        self.comboBox.setEditable(False)
        self.comboBox.setMaxVisibleItems(10)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setDuplicatesEnabled(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout.addWidget(self.comboBox_2)
        self.comboBox_3 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.verticalLayout.addWidget(self.comboBox_3)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet("QLineEdit {\n"
" border: 2.5px solid gray;\n"
" border-radius: 7px;\n"
" background-color: rgb(214, 214, 214);\n"
"    \n"
"    \n"
"    color: rgb(113, 113, 113)\n"
"}")
        self.lineEdit_8.setText("")
        self.lineEdit_8.setCursorPosition(0)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout.addWidget(self.lineEdit_8)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
" border: 2.5px solid gray;\n"
" border-radius: 7px;\n"
" background-color: rgb(214, 214, 214);\n"
"    \n"
"    \n"
"    color: rgb(113, 113, 113)\n"
"}")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setCursorPosition(0)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
" border: 2.5px solid gray;\n"
" border-radius: 7px;\n"
" background-color: rgb(214, 214, 214);\n"
"    \n"
"    \n"
"    color: rgb(113, 113, 113)\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
" border: 2.5px solid gray;\n"
" border-radius: 7px;\n"
" background-color: rgb(214, 214, 214);\n"
"    \n"
"    \n"
"    color: rgb(113, 113, 113)\n"
"}")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout.addWidget(self.lineEdit_5)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
" border: 2.5px solid gray;\n"
" border-radius: 7px;\n"
" background-color: rgb(214, 214, 214);\n"
"    \n"
"    \n"
"    color: rgb(113, 113, 113)\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("QLineEdit {\n"
" border: 2.5px solid gray;\n"
" border-radius: 7px;\n"
" background-color: rgb(214, 214, 214);\n"
"    \n"
"    \n"
"    color: rgb(113, 113, 113)\n"
"}")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout.addWidget(self.lineEdit_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("QLineEdit {\n"
" border: 2.5px solid gray;\n"
" border-radius: 7px;\n"
" background-color: rgb(214, 214, 214);\n"
"    \n"
"    \n"
"    color: rgb(113, 113, 113)\n"
"}")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout.addWidget(self.lineEdit_7)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 450, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 10, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(110, 60, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)

        self.pushButton_4.clicked.connect(self.openform1)
        self.pushButton_4.clicked.connect(Form.close)
        self.pushButton_3.clicked.connect(self.requirementfunction)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" color:#4f5a66;\">Your Requirment</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("Form", "Building"))
        self.comboBox.setItemText(1, _translate("Form", "Flat"))
        self.comboBox.setItemText(2, _translate("Form", "Villa"))
        self.comboBox.setItemText(3, _translate("Form", "Farms"))
        self.comboBox_2.setItemText(0, _translate("Form", "EAST OPEN"))
        self.comboBox_2.setItemText(1, _translate("Form", "WEST OPEN"))
        self.comboBox_2.setItemText(2, _translate("Form", "SOUTH OPEN"))
        self.comboBox_2.setItemText(3, _translate("Form", "NORTH OPEN"))
        self.comboBox_3.setItemText(0, _translate("Form", "Construction & Architect"))
        self.comboBox_3.setItemText(1, _translate("Form", "Architect"))
        self.lineEdit_8.setPlaceholderText(_translate("Form", "Your Name"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", "Location"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "Yards"))
        self.lineEdit_5.setPlaceholderText(_translate("Form", "Date Of Completion"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "No.Of Rooms"))
        self.lineEdit_6.setPlaceholderText(_translate("Form", "No.Of Floor"))
        self.lineEdit_7.setPlaceholderText(_translate("Form", "Parking Size"))
        self.pushButton_3.setText(_translate("Form", "Submit"))
        self.pushButton_4.setText(_translate("Form", "BACK"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
