# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'third1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Forms(object):

    def openformss(self):
        from seconds1 import Ui_Form
        self.Form = QtWidgets.QWidget()
        self.ui = Ui_Form()
        self.ui.setupUi(self.Form)
        self.Form.show()

    def openforms1(self):
        from four2 import Ui_Formsss
        self.Form = QtWidgets.QWidget()
        self.ui = Ui_Formsss()
        self.ui.setupUi(self.Form)
        self.Form.show()

    def registerfunction(self):
        first = self.lineEdit_2.text()
        last = self.lineEdit_6.text()
        cnic = self.lineEdit_3.text()
        email = self.lineEdit_4.text()
        phone = self.lineEdit_7.text()
        user = self.lineEdit_5.text()
        password = self.lineEdit.text()

        if len(first) == 0 or len(last) == 0 or len(cnic) == 0 or len(email) == 0 or len(phone) == 0 or len(
                user) == 0 or len(password) == 0:
            self.label_2.setText("please fill all the required field ")


        else:
            self.pushButton_5.clicked.connect(self.openforms1)
            #self.pushButton_5.clicked.connect(Form.close)
            conn = sqlite3.connect('register.db')
            cur = conn.cursor()
            user_info = [first, last, cnic, email, phone, user, password]
            cur.execute('INSERT INTO reg(firstname,lastname,cnic,email,phone,username,password) VALUES (?,?,?,?,?,?,?)',
                        user_info)

            conn.commit()
            conn.close()
            self.label_2.setText("your are register go next ")
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(521, 501)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 531, 511))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(-10, -20, 581, 521))
        self.label.setStyleSheet("border-image: url(C:/Users/F I ENTERPRISES/Documents/ise project/ise project 2k22/login.jpeg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(150, 30, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgba(79, 90, 102)")
        self.label_4.setObjectName("label_4")
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(110, 120, 301, 301))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("QLineEdit {\n"
" border: 3px solid gray;\n"
" border-radius: 10px;\n"
" background-color: rgb(214, 214, 214);\n"
"    \n"
"    \n"
"    color: rgb(113, 113, 113)\n"
"}")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setCursorPosition(0)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 5, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
" border: 3px solid gray;\n"
" border-radius: 10px;\n"
" background-color: rgb(214, 214, 214);\n"
"    \n"
"    \n"
"    color: rgb(113, 113, 113)\n"
"}")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setCursorPosition(0)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 6, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
" border: 3px solid gray;\n"
" border-radius: 10px;\n"
" background-color: rgb(214, 214, 214);\n"
"    \n"
"    \n"
"    color: rgb(113, 113, 113)\n"
"}")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setCursorPosition(0)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 3, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
" border: 2.5px solid gray;\n"
" border-radius: 10px;\n"
" background-color: rgb(214, 214, 214);\n"
"    \n"
"    \n"
"    color: rgb(113, 113, 113)\n"
"}")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setCursorPosition(0)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 4, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("QLineEdit {\n"
" border: 2.5px solid gray;\n"
" border-radius: 10px;\n"
" background-color: rgb(214, 214, 214);\n"
"    \n"
"    \n"
"    color: rgb(113, 113, 113)\n"
"}")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setCursorPosition(0)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 2, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
" border: 3px solid gray;\n"
" border-radius: 10px;\n"
" background-color: rgb(214, 214, 214);\n"
"    \n"
"    \n"
"    color: rgb(113, 113, 113)\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 9, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
" border: 2.5px solid gray;\n"
" border-radius: 10px;\n"
" background-color: rgb(214, 214, 214);\n"
"    \n"
"    \n"
"    color: rgb(113, 113, 113)\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 430, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.error1_2 = QtWidgets.QLabel(self.widget)
        self.error1_2.setGeometry(QtCore.QRect(240, 90, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.error1_2.setFont(font)
        self.error1_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.error1_2.setText("")
        self.error1_2.setObjectName("error1_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(120, 80, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 10, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(430, 10, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4.clicked.connect(self.openformss)
        self.pushButton_4.clicked.connect(Form.close)

        self.pushButton_3.clicked.connect(self.registerfunction)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\">Registration</p></body></html>"))
        self.lineEdit_7.setPlaceholderText(_translate("Form", "Phone Number"))
        self.lineEdit_5.setPlaceholderText(_translate("Form", "User Name"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "CNIC"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", "Email Adress"))
        self.lineEdit_6.setPlaceholderText(_translate("Form", "Last Name"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Password"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "First Name"))
        self.pushButton_3.setText(_translate("Form", "Submit"))
        self.pushButton_4.setText(_translate("Form", "BACK"))
        self.pushButton_5.setText(_translate("Form", "NEXT"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Forms()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
